FROM node:18-alpine

# Create app directory

WORKDIR /tmp/node-app

ENV NODE_SERVER_PORT=<%- serverPort %>

COPY . .

RUN npm install

WORKDIR /tmp/node-app/<%- clientRootDir %>

RUN npm run build

WORKDIR /tmp/node-app/<%- nodeServerRootDir %>

RUN npm run build

WORKDIR /usr/app/

RUN cp -r /tmp/node-app//<%- nodeServerRootDir %>dist .
RUN rm -rf /tmp/node-app

EXPOSE <%- serverPort %>

ENTRYPOINT ["node", "/usr/app/main.js" ]
