FROM node:18-alpine

# Create app directory

WORKDIR /usr/node-app

ENV NODE_SERVER_PORT=<%- serverPort %>
ENV CYPRESS_INSTALL_BINARY=0

COPY . .

RUN npm install
RUN npm run --workspace server build
RUN npm run --workspace client build
RUN npm cache clean --force
RUN rm -rf target tmp

EXPOSE <%- serverPort %>

ENTRYPOINT ["node", "/usr/node-app/<%- nodeServerRootDir %>dist/main.js" ]
