import { readFile } from 'node:fs/promises';

import { TEMPLATES_WEBAPP_SOURCES_DIR } from 'generator-jhipster';
import BaseApplicationGenerator from 'generator-jhipster/generators/base-application';
import { getEnumInfo } from 'generator-jhipster/generators/base-application/support';
import { createNeedleCallback } from 'generator-jhipster/generators/base-core/support';
import { mutateData } from 'generator-jhipster/utils';

import { SERVER_NODEJS_SRC_DIR } from '../generator-nodejs-constants.js';

import { entityFiles } from './entity-files.js';
import { serverFiles } from './files.js';

const fieldTypes = {
  Boolean: 'boolean',
  Integer: 'number',
  Long: 'number',
  Float: 'number',
  Double: 'number',
  BigDecimal: 'number',
  String: 'string',
  UUID: 'string',
  // Without a column type, TypeORM gives a Date the date-time type of the database in use.
  Instant: 'Date',
  ZonedDateTime: 'Date',
};

const dbTypes = {
  Boolean: 'boolean',
  Integer: 'integer',
  Long: 'bigint',
  Float: 'float',
  Double: 'double precision',
  BigDecimal: 'decimal',
  LocalDate: 'date',
  AnyBlob: 'blob',
  ImageBlob: 'blob',
  Blob: 'blob',
  TextBlob: 'blob',
  'byte[]': 'blob',
};

/**
 * Column types replacing the ones of dbTypes for a prodDatabaseType: the entities are shared by the prod database and by
 * better-sqlite3 (dev and test), so a type must be supported by TypeORM for both drivers. An undefined type omits it,
 * TypeORM then gives the type of the database for the TypeScript type (Boolean: bit on SQL Server, number on Oracle).
 * A byte[] field is an ImageBlob or an AnyBlob, a TextBlob is a byte[] field with a text content.
 */
const prodDatabaseColumnTypes = {
  // bytea is not a SQLite type: the blobs are kept as text, like the base64 strings the API exchanges.
  postgresql: { 'byte[]': 'text', TextBlob: 'text' },
  // SQL Server has no boolean type, and neither bit nor its binary types are SQLite ones.
  mssql: { Boolean: undefined, 'byte[]': 'text', TextBlob: 'text' },
  // Oracle has neither boolean nor bigint (integer is NUMBER(38)).
  oracle: { Boolean: undefined, Long: 'integer', TextBlob: 'clob' },
};

/** Enum column types by prodDatabaseType, simple-enum otherwise: Oracle has no simple-enum. */
const enumColumnTypes = {
  postgresql: 'varchar',
  oracle: 'varchar',
};

const databaseDrivers = {
  mongodb: 'mongodb',
  mysql: 'mysql2',
  postgresql: 'pg',
  oracle: 'oracledb',
  mssql: 'mssql',
};

const databaseDevDrivers = {
  mongodb: 'mongodb-memory-server',
  mysql: 'better-sqlite3',
  postgresql: 'better-sqlite3',
  oracle: 'better-sqlite3',
  mssql: 'better-sqlite3',
};

export default class extends BaseApplicationGenerator {
  oldNodejsVersion;
  existingNodejsVersion;
  nodejsPackageJson;

  async beforeQueue() {
    await this.dependsOnJHipster('jhipster-nodejs:node-server:bootstrap');
    await this.dependsOnJHipster('server');
  }

  get [BaseApplicationGenerator.INITIALIZING]() {
    return this.asInitializingTaskGroup({
      async initializing() {
        this.existingNodejsVersion = this.blueprintConfig.nodejsVersion;
        this.oldNodejsVersion = this.existingNodejsVersion ?? '3.0.0';
        this.nodejsPackageJson = JSON.parse((await readFile(this.templatePath('../../../package.json'), 'utf-8')).toString());
        this.blueprintConfig.nodejsVersion = this.nodejsPackageJson.version;
      },
    });
  }

  get [BaseApplicationGenerator.CONFIGURING]() {
    return this.asConfiguringTaskGroup({
      async configuringTemplateTask() {
        const { prodDatabaseType, databaseType } = this.jhipsterConfigWithDefaults;
        const databaseTypeMongodb = (prodDatabaseType ?? databaseType) === 'mongodb';
        this.jhipsterConfig.databaseType = databaseTypeMongodb ? 'mongodb' : 'sql';
        if (databaseTypeMongodb) {
          this.jhipsterConfig.prodDatabaseType = 'mongodb';
        }
      },
      keepSyncUserWithIdp() {
        // OAuth2 applications generated before 4.1.1 always synchronized their users, keep it for them. Not for an
        // application generated by this version itself (a development version records the version it will release).
        if (
          this.existingNodejsVersion &&
          this.isVersionLessThan(this.existingNodejsVersion, '4.1.1') &&
          this.isVersionLessThan(this.existingNodejsVersion, this.nodejsPackageJson.version) &&
          this.jhipsterConfigWithDefaults.authenticationType === 'oauth2' &&
          this.jhipsterConfig.syncUserWithIdp === undefined
        ) {
          this.jhipsterConfig.syncUserWithIdp = true;
        }
      },
    });
  }

  get [BaseApplicationGenerator.COMPOSING]() {
    return this.asComposingTaskGroup({
      async composingTemplateTask() {
        await this.composeWithJHipster('docker');
      },
    });
  }

  get [BaseApplicationGenerator.LOADING]() {
    return this.asLoadingTaskGroup({
      async loadingTemplateTask({ application }) {
        application.nodeServerDependencies = {};
        this.loadNodeDependenciesFromPackageJson(application.nodeServerDependencies, this.templatePath('../resources/package.json'));
      },
    });
  }

  get [BaseApplicationGenerator.PREPARING]() {
    return this.asPreparingTaskGroup({
      drivers({ applicationDefaults }) {
        applicationDefaults({
          __override__: false,
          nodeProdDatabaseDriver: ({ databaseType, prodDatabaseType = databaseType }) => databaseDrivers[prodDatabaseType],
          nodeDevDatabaseDriver: ({ databaseType, prodDatabaseType = databaseType }) => databaseDevDrivers[prodDatabaseType],
          nodeProdDatabaseType: ({ databaseType, prodDatabaseType = databaseType }) =>
            prodDatabaseType === 'postgresql' ? 'postgres' : prodDatabaseType,
          nodeDevDatabaseType: ({ databaseType, devDatabaseType = databaseType }) =>
            devDatabaseType === 'postgresql' ? 'postgres' : devDatabaseType,
        });
      },
      async source({ source }) {
        source.addEntityToNodeConfig = ({ entityFileName, persistClass }) =>
          this.editFile(
            `${SERVER_NODEJS_SRC_DIR}/src/orm.config.ts`,
            createNeedleCallback({
              needle: 'add-entity-to-ormconfig-imports',
              contentToAdd: `import { ${persistClass} } from './domain/${entityFileName}.entity';`,
            }),
            createNeedleCallback({
              needle: 'add-entity-to-ormconfig-entities',
              contentToAdd: `${persistClass},`,
            }),
          );
        source.addEntityToAppModule = ({ entityClass, entityFileName }) =>
          this.editFile(
            `${SERVER_NODEJS_SRC_DIR}/src/app.module.ts`,
            createNeedleCallback({
              needle: 'jhipster-needle-add-entity-module-to-main-import',
              contentToAdd: `import { ${entityClass}Module } from './module/${entityFileName}.module';`,
            }),
            createNeedleCallback({
              needle: 'jhipster-needle-add-entity-module-to-main',
              contentToAdd: `${entityClass}Module,`,
            }),
          );
      },
      async preparing({ application }) {
        application.typeormOrderSupport = !application.databaseTypeMongodb;
        application.typeormRelationsSupport = !application.databaseTypeMongodb;
      },
    });
  }

  get [BaseApplicationGenerator.LOADING_ENTITIES]() {
    return this.asLoadingEntitiesTaskGroup({
      async loadingEntitiesTemplateTask({ entitiesToLoad }) {
        for (const entity of entitiesToLoad) {
          entity.entityBootstrap.dto = true;
        }
      },
    });
  }

  get [BaseApplicationGenerator.PREPARING_EACH_ENTITY_FIELD]() {
    return this.asPreparingEachEntityFieldTaskGroup({
      async preparingEachEntityTemplateTask({ application, field }) {
        const { fieldType } = field;
        if (field.skipServer) return;

        if (field.fieldValues) {
          mutateData(field, {
            __override__: true,
            nodejsFieldType: fieldType,
            nodejsColumnType: enumColumnTypes[application.prodDatabaseType] ?? 'simple-enum',
          });
        } else {
          const columnTypes = { ...dbTypes, ...prodDatabaseColumnTypes[application.prodDatabaseType] };
          mutateData(field, {
            __override__: true,
            nodejsFieldType: fieldTypes[fieldType] ?? 'any',
            nodejsColumnType: columnTypes[field.fieldTypeBlobContent === 'text' ? 'TextBlob' : fieldType],
          });
        }
      },
    });
  }

  get [BaseApplicationGenerator.DEFAULT]() {
    return this.asDefaultTaskGroup({
      prepareUserLoginVm({ application }) {
        // The class of the logged user's data: the DTO of the built-in User entity, prepared with the entities, else
        // UserDTO (OAuth2 without syncUserWithIdp has no built-in User).
        application.userLoginVmClass = application.user?.dtoClass ?? 'UserDTO';
      },
    });
  }

  get [BaseApplicationGenerator.WRITING]() {
    return this.asWritingTaskGroup({
      async cleanup({ application, control }) {
        if (control.existingProject) {
          await control.cleanupFiles(this.oldNodejsVersion, {
            '3.0.1': [
              '.server.eslintrc.json',
              '.server.eslintignore',
              'server/src/repository/authority.repository.ts',
              'server/src/repository/user.repository.ts',
              [application.authenticationTypeOauth2, 'node/src/security/password-util.ts'],
            ],
            '4.1.1': [
              [!application.generateUserManagement, 'server/src/web/rest/user.controller.ts', 'server/e2e/user.e2e-spec.ts'],
              [
                !application.generateBuiltInUserEntity,
                'server/src/domain/user.entity.ts',
                'server/src/service/mapper/user.mapper.ts',
                'server/src/service/user.service.ts',
                'server/src/module/user.module.ts',
                'server/src/web/rest/public.user.controller.ts',
              ],
              [
                !application.generateBuiltInAuthorityEntity,
                'server/src/domain/authority.entity.ts',
                'server/src/migrations/1570200490072-SeedUsersRoles.ts',
              ],
            ],
          });
        }
      },
      async writingTemplateTask({ application }) {
        await this.writeFiles({
          sections: serverFiles,
          context: application,
        });
      },
    });
  }

  get [BaseApplicationGenerator.WRITING_ENTITIES]() {
    return this.asWritingEntitiesTaskGroup({
      async cleanup({ control, entities }) {
        if (control.existingProject) {
          await control.cleanupFiles(this.oldNodejsVersion, {
            '3.0.1': entities.filter(e => !e.skipServer).map(e => `server/src/repository/${e.entityFileName}.repository.ts`),
          });
        }
      },
      async customEntityServerFiles({ application, entities }) {
        for (const entity of entities.filter(entity => !entity.skipServer && !entity.builtIn)) {
          if (application.databaseType === 'mongodb' && entity.relationships.length > 0) {
            throw new Error('relationships not supported in mongodb!');
          }

          await this.writeFiles({
            sections: entityFiles,
            context: { ...application, ...entity },
          });

          const webappEnumerationsDir = `${SERVER_NODEJS_SRC_DIR}/src/domain/enumeration/`;
          for (const field of entity.fields.filter(field => field.fieldIsEnum)) {
            const enumInfo = getEnumInfo(field, entity.clientRootFolder);
            await this.writeFile(
              this.fetchFromInstalledJHipster(
                `client/templates/${TEMPLATES_WEBAPP_SOURCES_DIR}app/entities/enumerations/enum.model.ts.ejs`,
              ),
              `${webappEnumerationsDir}${field.enumFileName}.ts`,
              enumInfo,
            );
          }
        }
      },
    });
  }

  get [BaseApplicationGenerator.POST_WRITING]() {
    return this.asPostWritingTaskGroup({
      adjustWorkspacePackageJson({ application }) {
        if (application.databaseTypeMongodb) {
          // download the mongod binary at install time, into a directory shared by all workspaces
          this.packageJson.merge({
            allowScripts: {
              'mongodb-memory-server': true,
            },
            config: {
              mongodbMemoryServer: {
                downloadDir: 'node_modules/.cache/mongodb-memory-server',
              },
            },
          });
        } else {
          // better-sqlite3 (dev and test database) downloads or builds its native binding at install time
          this.packageJson.merge({
            allowScripts: {
              'better-sqlite3': true,
            },
          });
        }
        if (application.clientFrameworkAngular) {
          this.packageJson.merge({
            overrides: {
              'browser-sync': application.nodeDependencies['browser-sync'],
            },
          });
        }
      },
      ignoreClientIssues({ application }) {
        if (application.clientFrameworkNo) return;
        // TODO use source.addEslintConfig
        this.editFile(
          `${application.clientRootDir}/eslint.config.ts`,
          createNeedleCallback({
            needle: 'eslint-add-config',
            contentToAdd: String.raw`{
  files: ["${this.relativeDir(application.clientRootDir, application.clientSrcDir)}**/*"],
  rules: { "@typescript-eslint/no-unsafe-return": "off" },
},`,
          }),
        );
      },
    });
  }

  get [BaseApplicationGenerator.POST_WRITING_ENTITIES]() {
    return this.asPostWritingEntitiesTaskGroup({
      async postWritingEntitiesTemplateTask({ entities, source }) {
        for (const entity of entities.filter(entity => !entity.skipServer)) {
          const { entityFileName, persistClass, entityClass } = entity;
          if (!entity.builtInUserManagement) {
            source.addEntityToNodeConfig({ entityFileName, persistClass });
          }
          if (!entity.builtIn) {
            source.addEntityToAppModule({ entityFileName, entityClass });
          }
        }
      },
    });
  }
}
