FROM node:12-alpine

# Create app directory

WORKDIR /usr/node-app

COPY . .

# install server deps

WORKDIR server

RUN npm install

# install client deps

WORKDIR ..

RUN npm install

EXPOSE 8081

ENTRYPOINT [ "npm", "run", "start:app" ]
