name: Test Integration Vue
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
permissions:
  contents: read
env:
  NODE_OPTIONS: --dns-result-order=ipv4first
  FORCE_COLOR: 2
jobs:
  applications:
    name: ${{ matrix.app-type }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    timeout-minutes: 40
    defaults:
      run:
        working-directory: ${{ github.workspace }}/app
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
        os: [ubuntu-latest]
        app-type:
          - monolith-vue-jwt-i18n-jdl
          - monolith-vue-oauth2-i18n-jdl
          - monolith-vue-mongodb-prod-jdl
        include:
          - app-type: monolith-vue-jwt-i18n-jdl
            app-folder: monolith-client-auth-i18n-template-jdl
            entity: import-jdl
            e2e: jwt
          - app-type: monolith-vue-oauth2-i18n-jdl
            app-folder: monolith-client-auth-i18n-template-jdl
            entity: import-jdl
            e2e: oauth2
          - app-type: monolith-vue-mongodb-prod-jdl
            app-folder: monolith-client-database-prod-template-jdl
            entity: import-jdl
            e2e: 'false'
    env:
      NHI_APP: ${{ matrix.app-type }}
      NHI_APP_FOLDER: ${{ matrix.app-folder }}
      NHI_ENTITY: ${{ matrix.entity }}
      NHI_E2E: ${{ matrix.e2e }}

    steps:
      - uses: actions/checkout@v4
        with:
          path: generator-jhipster-nodejs
          fetch-depth: 2
      - uses: jhipster/actions/setup-runner@v0
        with:
          node-version: ${{ matrix.node-version }}
          binary-dir: ${{ github.workspace }}/generator-jhipster-nodejs/cli/
      - run: npm install
        working-directory: ${{ github.workspace }}/generator-jhipster-nodejs
      - run: cli.cjs generate-sample $NHI_APP_FOLDER --template-name $NHI_APP --skip-jhipster-dependencies --skip-install
      - uses: jhipster/actions/compare-sample@v0
        id: compare
        if: >-
          github.event.pull_request &&
          !contains(github.event.pull_request.labels.*.name, 'pr: disable-compare')
        with:
          generator-path: generator-jhipster-nodejs
          cmd: cli.cjs generate-sample $NHI_APP_FOLDER --template-name $NHI_APP --skip-jhipster-dependencies --skip-install
      - name: 'INSTALL DEPENDENCIES of generated app'
        run: npm install
        if: steps.compare.outputs.equals != 'true'
      - name: 'RUN UNIT TESTS of generated app'
        run: npm test --workspaces
        if: steps.compare.outputs.equals != 'true'
      - name: 'RUN SERVER E2E TESTS of generated app'
        run: npm run test:server:e2e
        if: steps.compare.outputs.equals != 'true'
      - name: 'BUILD AND RUN SERVER APP'
        run: npm run app:up
        if: steps.compare.outputs.equals != 'true'
      - name: 'START APP WITH EVENTUAL CLIENT E2E TESTS'
        run: npm run e2e:headless --workspace client
        if: matrix.e2e != 'false' && steps.compare.outputs.equals != 'true'
        id: e2e
      - name: Store cypress screenshots
        uses: actions/upload-artifact@v4
        if: always() && steps.e2e.outcome == 'failure'
        with:
          name: screenshots-${{ matrix.app-type }}
          path: ${{ github.workspace }}/app/**/cypress/screenshots
      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
  check-vue-applications:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [applications]
    if: always()
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'
          if [ 'skipped' == '${{ needs.applications.result }}' ] || [ 'success' == '${{ needs.applications.result }}' ] || [ 'closed' == '${{ github.event.action }}' ]; then
            exit 0
          fi
          exit 1
