name: Test Integration React
concurrency:
  # Group PRs by head_ref, push to main branch by commit id, and others branch by ref.
  group: ${{ github.workflow }}-${{ github.head_ref || (github.ref == 'refs/heads/main' && github.sha) || github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
permissions:
  contents: read
env:
  NODE_OPTIONS: --dns-result-order=ipv4first
  FORCE_COLOR: 2
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - id: build
        run: |
          npm install
          ./cli/cli.cjs github-build-matrix react
  samples:
    name: ${{ matrix.job-name || matrix.sample }}
    runs-on: ${{ matrix.os }}
    needs: build-matrix
    defaults:
      run:
        working-directory: ${{ github.workspace }}/app
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.build-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v4
        with:
          path: generator-jhipster-nodejs
          fetch-depth: 2
      - uses: jhipster/actions/setup-runner@v0
        with:
          node-version: ${{ matrix.node-version }}
          binary-dir: ${{ github.workspace }}/generator-jhipster-nodejs/cli/
      - run: npm install
        working-directory: ${{ github.workspace }}/generator-jhipster-nodejs
      - run: cli.cjs generate-sample ${{ matrix.sample }} --samples-group ${{ matrix.samples-group }} --skip-jhipster-dependencies --skip-install ${{ matrix.extra-args }}
      - uses: jhipster/actions/compare-sample@v0
        id: compare
        if: >-
          github.event.pull_request &&
          !contains(github.event.pull_request.labels.*.name, 'pr: disable-compare')
        with:
          generator-path: generator-jhipster-nodejs
          cmd: cli.cjs generate-sample ${{ matrix.sample }} --samples-group ${{ matrix.samples-group }} --skip-jhipster-dependencies --skip-install ${{ matrix.extra-args }}
      - name: 'INSTALL DEPENDENCIES of generated app'
        run: npm install
        if: steps.compare.outputs.equals != 'true'
      - name: 'RUN UNIT TESTS of generated app'
        run: npm test --workspaces
        if: steps.compare.outputs.equals != 'true'
      - name: 'RUN SERVER E2E TESTS of generated app'
        run: npm run test:server:e2e
        if: steps.compare.outputs.equals != 'true'
      - name: 'BUILD AND RUN SERVER APP'
        run: npm run app:up
        if: steps.compare.outputs.equals != 'true'
      - name: 'START APP WITH EVENTUAL CLIENT E2E TESTS'
        run: npm run e2e:headless --workspace client
        if: matrix.e2e != 'false' && steps.compare.outputs.equals != 'true'
        id: e2e
      - name: Store cypress screenshots
        uses: actions/upload-artifact@v4
        if: always() && steps.e2e.outcome == 'failure'
        with:
          name: screenshots-${{ matrix.job-name || matrix.sample }}
          path: ${{ github.workspace }}/app/**/cypress/screenshots
      - name: Dump docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
  check-react-applications:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [samples]
    if: always()
    steps:
      - run: |
          echo '${{ toJSON(needs) }}'
          if [ 'skipped' == '${{ needs.samples.result }}' ] || [ 'success' == '${{ needs.samples.result }}' ] || [ 'closed' == '${{ github.event.action }}' ]; then
            exit 0
          fi
          exit 1
